language: csharp
solution: Arbeitszeitdokumentation.sln
mono:
  - latest
script:
  - xbuild /p:Configuration=Release Arbeitszeitdokumentation.sln
  - find . -not -path '*/\.*'
  - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./Arbeitszeitdokumentation.Tests/bin/Release/Arbeitszeitdokumentation.Tests.dll