language: csharp
solution: Arbeitszeitdokumentation.sln
mono:
  - latest
script:
  - xbuild /p:Configuration=Release Arbeitszeitdokumentation.sln
  - find . -not -path '*/\.*'
  - mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./Arbeitszeitdokumentation/bin/Release/nunit.framework.dll